
BLENDER="C:\work\Blender\blender.exe"

DIST=../dist

all : \
$(DIST)/hexapod.pnct \
$(DIST)/hexapod.scene \
$(DIST)/FlashLight.pnct \
$(DIST)/FlashLight.scene \

$(DIST)/hexapod.scene : hexapod.blend export-scene.py
	$(BLENDER) --background --python export-scene.py -- "hexapod.blend:Main" "$(DIST)/hexapod.scene"

$(DIST)/hexapod.pnct : hexapod.blend export-meshes.py
	$(BLENDER) --background --python export-meshes.py -- "hexapod.blend:Main" "$(DIST)/hexapod.pnct"

$(DIST)/FlashLight.scene : FlashLight.blend export-scene.py
	$(BLENDER) --background --python export-scene.py -- "FlashLight.blend:Main" "$(DIST)/FlashLight.scene"

$(DIST)/FlashLight.pnct : FlashLight.blend export-meshes.py
	$(BLENDER) --background --python export-meshes.py -- "FlashLight.blend:Main" "$(DIST)/FlashLight.pnct"
